### ISSUE TITLE
Cast Icon not showing on Vista/Chrome 41/Google Cast 15

### ISSUE THREAD

**Issue by twinkle-nl** [SKAhack/cast-bandcamp#6]
After 
- installing Google Cast Extension
- installing Bandcast extension
- restarting Chrome browser
- navigating to bandcamp url

the Cast Icon is not showing up on the page. 
Google casting is possible though, mirroring the site 'as is' to my TV.

My setup is
- Windows Vista Home Basic SP2
- Pentium Dual CPU T2390, 1,87GHZ
- Chrome Version 41.0.2272.101 m
- Google Cast 15.226.0.1
- Bandcast 0.0.4

Would be great if it would work!

**Comment by SKAhack** [comment]
Thank you for your report :+1: 
Could you give me a URL?

This problem is may be unsupport page. Bandcast is supported only "Album page".

Album page is: https://atrocitysolution.bandcamp.com/album/lost-remedies
Track page is: https://atrocitysolution.bandcamp.com/track/the-introduction-pt-2
Band top page is: https://atrocitysolution.bandcamp.com/

**Comment by twinkle-nl** [comment]
Thank you for your quick response!
And indeed this was the problem.
Although it looked like an album page

https://liquidsounddesign.bandcamp.com/releases

it was actually a 'release' page (?)

But navigating to this url showed the Cast Icon and clicking it worked as desired:

http://liquidsounddesign.bandcamp.com/album/all-is-not-lost-but-where-is-it

So not a real issue.
Thanks again!

**Comment by SKAhack** [comment]
I'll support 'release page' and 'band top page'. next update.

Thanks.
